### PR TITLE
linux-starfive-dev: update VF2 kernel to V3.6.1 SDK

### PR DESCRIPTION
**Pull request by rmsyn**

### CODE REVIEW

**Comment by kraj** [comment]
@rmsyn there are other components also used from SDK, would those recipes will need bump as well. I woiuld like to keep the SDK pieces in sync as much as possible.

**Comment by rmsyn** [comment]
> there are other components also used from SDK, would those recipes will need bump as well.

Right, I wasn't sure how much was pulled in, was mostly focused on the kernel piece.

>  I woiuld like to keep the SDK pieces in sync as much as possible.

Definitely, I'll bump those revisions as well.

**Comment by Fishwaldo** [comment]
I think there were also fixes for the JPU/VPU and gstreamer/omx (and probably check anything new in Mesa?)

**Comment by rmsyn** [comment]
> I think there were also fixes for the JPU/VPU and gstreamer/omx (and probably check anything new in Mesa?)

Are these extra patch files, or revisions on`starfive-tech` repo(s)?

**Comment by Fishwaldo** [comment]
I think also in the buildroot repo

**Comment by Fishwaldo** [comment]
I think the gstreamer recipe is based on patches

**Comment by rmsyn** [comment]
> I think the gstreamer/Mesa recipes is based on patches

Alright, so I found the patches for `gstreamer`, here:

https://github.com/riscv/meta-riscv/blob/master/recipes-multimedia/gstreamer/gstreamer1.0-omx_%25.bbappend

I'm not sure what the procedure is for updating these patches. Happy to dig into some documentation, or work with someone more experienced.

The `vpu` stuff looks like it is just building on files downloaded by another recipe(s).

https://github.com/riscv/meta-riscv/tree/master/recipes-multimedia/vpu

> I think also in the buildroot repo

I searched for that in the recipes, but couldn't find a reference outside of what look like toolchain and makefile:

- https://github.com/riscv/meta-riscv/blob/master/recipes-multimedia/vpu/libsf-wave420l/WaveEncoder_yocto.mak#L46
- https://github.com/riscv/meta-riscv/blob/master/recipes-multimedia/vpu/libsf-codaj12/codaj12_yocto.mak#L56
- https://github.com/riscv/meta-riscv/blob/master/recipes-multimedia/vpu/libsf-codaj12/codaj12_yocto.mak#L89
- https://github.com/riscv/meta-riscv/blob/master/recipes-multimedia/vpu/libsf-wave511/WaveDecode_yocto.mak#L60
  - this one is commented out

The SDK `buildroot` has an updated revision, just not sure where to put that in the `meta-riscv` recipes.

**Comment by kraj** [comment]
> > I think the gstreamer/Mesa recipes is based on patches
> 
> Alright, so I found the patches for `gstreamer`, here:
> 
> https://github.com/riscv/meta-riscv/blob/master/recipes-multimedia/gstreamer/gstreamer1.0-omx_%25.bbappend
> 
> I'm not sure what the procedure is for updating these patches. Happy to dig into some documentation, or work with someone more experienced.

I think this is a bit different that Buildroot SDK from VisionFive2, since the sdk is at 1.18.x version but with yocto/OE we are moving forward and currently at 1.22.x, I dont know how long we can keep stretching but we will try.

> 
> The `vpu` stuff looks like it is just building on files downloaded by another recipe(s).
> 
> https://github.com/riscv/meta-riscv/tree/master/recipes-multimedia/vpu
> 
> > I think also in the buildroot repo
> 
> I searched for that in the recipes, but couldn't find a reference outside of what look like toolchain and makefile:
> 
> * https://github.com/riscv/meta-riscv/blob/master/recipes-multimedia/vpu/libsf-wave420l/WaveEncoder_yocto.mak#L46
> * https://github.com/riscv/meta-riscv/blob/master/recipes-multimedia/vpu/libsf-codaj12/codaj12_yocto.mak#L56
> * https://github.com/riscv/meta-riscv/blob/master/recipes-multimedia/vpu/libsf-codaj12/codaj12_yocto.mak#L89
> * https://github.com/riscv/meta-riscv/blob/master/recipes-multimedia/vpu/libsf-wave511/WaveDecode_yocto.mak#L60
>   
>   * this one is commented out
> 
> The SDK `buildroot` has an updated revision, just not sure where to put that in the `meta-riscv` recipes.

these are using recipes-bsp/common/visionfive2-firmware.inc to fetch the SDK bits. which I think this patch has updated.

**Comment by rmsyn** [comment]
> I think this is a bit different that Buildroot SDK from VisionFive2, since the sdk is at 1.18.x version but with yocto/OE we are moving forward and currently at 1.22.x, I dont know how long we can keep stretching but we will try.

Alright, I'm running test builds now.

Hopefully, the last remaining bits of drivers will be upstreamed, and we can switch to vanilla kernel/buildroot.

**Pull request merged**
