### PR TITLE
Upgrade the kernels to use the latest branchs

### PR DESCRIPTION
**Pull request by alistair23**

### CODE REVIEW

**Comment by kraj** [comment]
@alistair23 can you also merge changes from https://github.com/riscv/meta-riscv/pull/40 into your pull ? if something is missing

**Comment by alistair23** [comment]
Ok, updated

**Comment by kraj** [comment]
thanks

**Comment by pino-kim** [comment]
Dear @alistair23, @kraj 
It just my question.
see risc-v kernel site(https://git.kernel.org/pub/scm/linux/kernel/git/palmer/riscv-linux.git)
remain 4.18's branch. so remove 4.14's bbfile and 4.15's bbfile as outdate kernel version?

**Comment by kraj** [comment]
thats right

**Pull request merged**
