### PR TITLE
gdb: Remove the RISC-V GDB

### PR DESCRIPTION
**Pull request by alistair23**
Now that GDB 8.3 has been merged into the meta layer we no longer need a
custom GDB version.

Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
Thanks!

**Comment by kraj** [comment]
lgtm

**Comment by kraj** [comment]
we need to merge https://github.com/riscv/meta-riscv/pull/142 first and branch out for thud and warrior which I have already done

**Comment by alistair23** [comment]
Thanks Khem. This would still work with older releases, the user would just get a less useful GDB version included.

**Pull request merged**
