### PR TITLE
Uninative

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by pino-kim** [comment]
Dear @kraj 
this PR is relate issue #26 ?

**Comment by kraj** [comment]
@pino-kim I am trying to fix this problem so please try I have merged

**Comment by pino-kim** [comment]
Dear @kraj
Oh Thanks. I am already ready to build it.
Could you find what is problem?

**Comment by kraj** [comment]
I think it could be due to uninative not being inherited. So please build from scratch and try again

**Pull request merged**
