### PR TITLE
linux-nezha/defconfig: update led config name

### PR DESCRIPTION
**Pull request by twoerner**
This configuration parameter was renamed from R329 to A100 in v5 of this patch set (which is currently up to v7).

Signed-off-by: Trevor Woerner <twoerner@gmail.com>

**- <recipename>: Short log / Statement of what needed to be changed.**
  
**-(Optional pointers to external resources, such as defect tracking)**
  
**-The intent of your change.**
  
**-(Optional, if it's not clear from above) how your change resolves the
issues in the first part.**
  
**-Tag line(s) at the end.**

**-Signed-off-by: Random J Developer <random@developer.example.org>**

### CODE REVIEW

**Review by kraj — APPROVED** [review]
LGTM, I think this could be a good candidate for upstream nezha kernel as well.

**Comment by twoerner** [comment]
Actually... the riscv/d1-wip branch adds a nezha_defconfig which has the updated naming:
https://github.com/smaeul/linux/commit/ca67838d84af4c9f85d06311c9e98e1adf46308f

**Comment by kraj** [comment]
@twoerner can you rebase it on master please?

**Review by alistair23 — APPROVED** [review]

**Comment by twoerner** [comment]
This pull request and https://github.com/riscv/meta-riscv/pull/387 were an "either/or" situation. They were 2 different ways to solve the same problem. Since https://github.com/riscv/meta-riscv/pull/387 has already been pulled, we no longer need this one.

**Pull request closed without merging**
