### PR TITLE
[RFC] Use OpenSBI by default

### PR DESCRIPTION
**Pull request by alistair23**
As this requires the 5.0 kernel this is just an RFC for those interested.

### CODE REVIEW

**Comment by kraj** [comment]
what does SBI get us

**Comment by alistair23** [comment]
To start it's an improved replacement of bbl.

The full release announcement is below:

OpenSBI is an open source implementation of the RISC-V Supervisor Binary
Interface (SBI). RISC-V SBI specifications are maintained as an independent project by the RISC-V Foundation in [Github].

This initial release of OpenSBI provides an implementation of the RISC-V SBI specifications version 0.1. These specifications define the legacy SBI interface currently in use by various products as well as by RISC-V QEMU virtual machines.

OpenSBI also implements SBI compliant early boot firmwares capable of handling various boot flows and payloads on various environments. OpenSBI firmwares have been tested with payloads such as U-Boot and Linux kernel, showing that these open firmwares can fully replace the legacy non-standard BBL intermediate boot loader.

The platforms supported with this first release are as follows.
* Sifive HiFive Unleashed board
* RISC-V QEMU *virt* and *sifive_u* virtual machines
* Kendryte K210 SoC based boards.

OpenSBI implementation can be easily extended by RISC-V platform vendors and System-on-Chip vendors to fit new hardware configurations.

As SBI specifications evolve and extend beyond the current base legacy
features, OpenSBI will be modified to provide a reference implementation for new SBI specifications.

More information on OpenSBI capabilities as well as a contribution guideline are available in OpenSBI documentation included with the source code in GitHub.

**Comment by kraj** [comment]
seems good to me. Lets wait for 5.0

**Comment by alistair23** [comment]
Closing this as the final changes will be more significant.

**Pull request closed without merging**
