### PR TITLE
openocd: Move to dynamic-layer for meta-oe

### PR DESCRIPTION
**Pull request by jpuhlman**
currently meta-riscv does not parse unless meta-oe is present.
It does not appear that anything explictly depends on openocd
in the layer.

Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>

### CODE REVIEW

**Comment by kraj** [comment]
I guess you missed moving openocd_riscv.bb to new location. but I think I would like you to try change `require` to `include` and see if that helps

**Comment by jpuhlman** [comment]
The move is there.
Here is the git log output from the branch of the pull request:

commit 514d66c19a77cd7febf83702d7233313a3d90e1e (HEAD -> master-jp, origin/master-jp)
Author: Jeremy Puhlman <jpuhlman@mvista.com>
Date:   Fri Feb 21 20:48:37 2020 +0000

    openocd: Move to dynamic-layer for meta-oe

    currently meta-riscv does not parse unless meta-oe is present.
    It does not appear that anything explictly depends on openocd
    in the layer.

    Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>

diff --git a/conf/layer.conf b/conf/layer.conf
index 315ba6d..7ddb7de 100644
--- a/conf/layer.conf
+++ b/conf/layer.conf
@@ -14,6 +14,8 @@ BBFILES_DYNAMIC += " \
     qt5-layer:${LAYERDIR}/dynamic-layers/qt5-layer/*/*/*.bbappend \
     virtualization-layer:${LAYERDIR}/dynamic-layers/virt-layer/*/*/*.bb \
     virtualization-layer:${LAYERDIR}/dynamic-layers/virt-layer/*/*/*.bbappend \
+    openembedded-layer:${LAYERDIR}/dynamic-layers/openembedded-layer/*/*/*.bb \
+    openembedded-layer:${LAYERDIR}/dynamic-layers/openembedded-layer/*/*/*.bbappend \
     \
 "

diff --git a/recipes-devtools/openocd/openocd_riscv.bb b/dynamic-layers/openembedded-layer/recipes-devtools/openocd/openocd_riscv.bb
similarity index 100%
rename from recipes-devtools/openocd/openocd_riscv.bb
rename to dynamic-layers/openembedded-layer/recipes-devtools/openocd/openocd_riscv.bb

**Comment by jpuhlman** [comment]
Changing it to include would resolve the parsing issue, but it would leave a broken recipe in the layer.

**Comment by kraj** [comment]
yes makes sense, somehow I did not see the move in email, it looks ok

**Pull request merged**
