### PR TITLE
Upgrade to U-Boot 2019.07

### PR DESCRIPTION
**Pull request by alistair23**
Update the bbappend to apply to 2019.07 and backport the new device tree bindings and SPI/MMC support. Now that we have SPI/MMC support we can update the u-boot boot script to try a TFTP load first and if that fails fall back to an MMC load. While we are at it let's update the README as well.

### CODE REVIEW

**Comment by alistair23** [comment]
This needs OpenSB 0.4 and U-Boot 2019.07 merged into OE-Core before it can be merged.

**Comment by alistair23** [comment]
Retest this please

**Comment by alistair23** [comment]
This one is also ready to be merged once the test passes.

**Comment by kraj** [comment]
Can you rebase this on latest master please ?

**Comment by alistair23** [comment]
Just rebased

**Pull request merged**
