### PR TITLE
BeagleV-Ahead board support

### PR DESCRIPTION
**Pull request by cordlandwehr**
This pull request brings initial support for the BeagleV-Ahead devices without the need of any external toolchain (as currently configured in the Beagleboard downstream repositories).
The patches are an initial request for feedback and not ready in the sense that the boot.ext4 generation needs a little bit more cleanups and I want to get the BeagleV-Ahead firmware blobs integrated. But a build should already create a bootable image.

### CODE REVIEW

**Comment by kraj** [comment]
Can you rebase it on latest master please ?

**Comment by cordlandwehr** [comment]
Already on it, but might take a little bit of time as I have make the u-boot fork compatible with GCC14 first.

**Comment by cordlandwehr** [comment]
This is still a very much WIP state, but better than before. As I do not have much time the next days, if anybody is eager to test/improve it, here is the status:
- the vendor u-boot now does compile with GCC14
- the patches are tested with kind of recent upstream master (poky at f66f8fa9f605d5dc39acb10226198b3ab40dcaa3)

Problems yet with this patch set:
- one has to manually run "bitbake virtual/kernel -c beaglev_img_deploy" to get boot.ext4 generated
- u-boot's install command is commented out due to install file issues
- the firmware files for beaglev-ahead are not yet packages

But well, it boots recent Kernel from eMMC. Good enough for a push I hope :)

**Comment by kraj** [comment]
> This is still a very much WIP state, but better than before. As I do not have much time the next days, if anybody is eager to test/improve it, here is the status:
> 
> * the vendor u-boot now does compile with GCC14
> * the patches are tested with kind of recent upstream master (poky at f66f8fa9f605d5dc39acb10226198b3ab40dcaa3)
> 
> Problems yet with this patch set:
> 
> * one has to manually run "bitbake virtual/kernel -c beaglev_img_deploy" to get boot.ext4 generated
> * u-boot's install command is commented out due to install file issues
> * the firmware files for beaglev-ahead are not yet packages
> 
> But well, it boots recent Kernel from eMMC. Good enough for a push I hope :)

should be good, can you turn this into proper PR instead of a draft then ?

**Pull request merged**
