### PR TITLE
Revert the OpenSBI and u-boot switch and ignore textrels in fish shell

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by pdp7** [comment]
@kraj was there a problem that required backing out the the change to switch to generic platform?

cc @atishp04 @lbmeng

**Comment by kraj** [comment]
> @kraj was there a problem that required backing out the the change to switch to generic platform?
> 
> cc @atishp04 @lbmeng

yes, I flashed the resulting fw_payload.bin.out and it does not boot and size has gone up from 700K to 2.6M for the payload
perhaps some knobs need to be enabled, but bootloader not booting is bad thats why the revert, until we figure out whats up
with this

**Comment by lbmeng** [comment]
Please try https://github.com/starfive-tech/u-boot/pull/17

**Comment by alistair23** [comment]
Yeah, I can confirm it doesn't work. I did test it but I must have flashed the wrong thing.

@lbmeng No luck with that branch either

**Comment by lbmeng** [comment]
> FW_FDT_PATH=beaglev-starlight-jh7100/jh7100-starlight.dtb

Where does this dtb come from? I was using the one in the StarFive U-Boot repo.

**Comment by alistair23** [comment]
It's the one from the kernel, should we use the u-boot one instead?

**Comment by lbmeng** [comment]
> It's the one from the kernel, should we use the u-boot one instead?

Yes.

**Comment by kraj** [comment]
> > It's the one from the kernel, should we use the u-boot one instead?
> 
> Yes.

@alistair23 can you sync with @esmil and update the DT in kernel too ?

**Comment by atishp04** [comment]
Here are the heads that works for me (rebooted 15/20 times)

OpenSBI:
54d7def6c254  lib: utils: Try other FDT drivers when we see SBI_ENODEV

U-Boot:
feda8aecd8fa starfive: beaglev: Disable SIFIVE_CLINT and enable RISCV_TIMER
(After applying Bin's PR[1] on top of https://github.com/starfive-tech/u-boot/tree/Fedora_VIC_7100_2021.04)
[1]https://github.com/starfive-tech/u-boot/pull/17

Kernel from esmil tree:
a22fc12294bf drivers/usb: Don't flush NULL values

**Comment by esmil** [comment]
@atishp04
> Here are the heads that works for me (rebooted 15/20 times)

What does that mean? That booting only worked 15 of 20 times?

**Comment by atishp04** [comment]
ha ha. No. I only tried 15/20 times :). Got bored of pressing the reset button ;)

**Comment by esmil** [comment]
> ha ha. No. I only tried 15/20 times :). Got bored of pressing the reset button ;)

Ok, good. Let's hope switich to upstream OpenSBI just fixes [this issue][] then. I should really try updating u-boot myself.
Is minicom still the way to go or is https://github.com/kprasadvnsi/JH71xx-tools easier?

[this issue]: https://github.com/starfive-tech/linux/issues/15

**Comment by kraj** [comment]
> Here are the heads that works for me (rebooted 15/20 times)
> 
> OpenSBI:
> 54d7def6c254 lib: utils: Try other FDT drivers when we see SBI_ENODEV
> 
> U-Boot:
> feda8aecd8fa starfive: beaglev: Disable SIFIVE_CLINT and enable RISCV_TIMER
> (After applying Bin's PR[1] on top of https://github.com/starfive-tech/u-boot/tree/Fedora_VIC_7100_2021.04)
> [1][starfive-tech/u-boot#17](https://github.com/starfive-tech/u-boot/pull/17)
> 
> Kernel from esmil tree:
> a22fc12294bf drivers/usb: Don't flush NULL values

Where did you get the device tree
From

**Comment by atishp04** [comment]
for opensbi + U-Boot payload : DTB comes from U-Boot
For kernel: It comes from kernel tree

I haven't tried passing the kernel tree to U-Boot or vice versa.

**Comment by kraj** [comment]
> Here are the heads that works for me (rebooted 15/20 times)
> 
> OpenSBI:
> 54d7def6c254 lib: utils: Try other FDT drivers when we see SBI_ENODEV
> 
> U-Boot:
> feda8aecd8fa starfive: beaglev: Disable SIFIVE_CLINT and enable RISCV_TIMER
> (After applying Bin's PR[1] on top of https://github.com/starfive-tech/u-boot/tree/Fedora_VIC_7100_2021.04)
> [1][starfive-tech/u-boot#17](https://github.com/starfive-tech/u-boot/pull/17)
> 
> Kernel from esmil tree:
> a22fc12294bf drivers/usb: Don't flush NULL values

I used exact same versions for openSBI and u-boot + 2patches you pointed out and it does not boot ends up with something like this

```
quit
    crc flash: 7791d106, crc ddr: 7791d106
                                          crc check PASSED

                                                          bootloader.
                                                                     bootloader version:210209-4547a8d
                                                                                                      ddr 0x00000000, 1M test
ddr 0x00100000, 2M test
DDR clk 2133M,Version: 210302-5aea32f
0 crc flash: 7791d106, crc ddr: 7791d106
                                        crc check PASSED

                                                        bootloader.

```

**Comment by alistair23** [comment]
PR opened: https://github.com/riscv/meta-riscv/pull/294

**Comment by kraj** [comment]
closing in favour of #294

**Pull request closed without merging**
