### PR TITLE
Kas support and Machine ReOrder

### PR DESCRIPTION
**Pull request by bhstalel**
Create kas folder containing common and specific YAML files for all machines and confs

Create common machine conf files for all boards and one SOC for JH7110

Update README for KAS mention

**NOTE:** Building test process is in progress. After testing the build process, one should test on real hardware if available.

### CODE REVIEW

**Comment by kraj** [comment]
any updates on this @bhstalel ? I see its still in Draft stage

**Comment by bhstalel** [comment]
@kraj I still did not find the right time to build all images, also I encountred some build failures as I found new machines in master branch, I will check this this weekend.

**Comment by bhstalel** [comment]
@kraj There are some build failures related to bugs in recipes, like non existing branch or something like that, should we merge this and then I work on those failures in other PR ?

**Comment by kraj** [comment]
> @kraj There are some build failures related to bugs in recipes, like non existing branch or something like that, should we merge this and then I work on those failures in other PR ?

OK. Can you post the nature of failures ( maybe errors ) here. ? if they are not something casued by this commit then we can merge it. I would like to know.

**Comment by bhstalel** [comment]
These are some errors:

* For `start64` build:

    u-boot-starfive_v2021.10.bb:do_deploy: tmp/work/star64-poky-linux/u-boot-starfive/v2021.10/uEnv-visionfive2.txt': 
    No such file or directory

* For `ae350-ax45mpè:

    11 dependency loops found

* For `visionfive`:

    linux-starfive-dev.bb:do_patch error

Without pasting the details of the errors, it seems like recipe's issues and not related to the KAS added feature.

Other builds are fine for: `nezha`, `base-riscv`, `beaglev` and `visionfive2` for the exception of when changing the machine on the same build tmp deploy it happens to fail on `do_create_spdx` tasks because they all share the same deploy folder and there are recipes that create the same spdx files,

for this I will add the support for the `multiconfig` feature to separate the tmp folders for each machine on separate PR later. Or I will check for other options on how to solve it.

**Review by kraj — APPROVED** [review]
lgtm

**Pull request merged**
