### PR TITLE
riscv: Enable SECURITY_CFLAGS and GLIBC PIE for rv32/rv64

### PR DESCRIPTION
**Pull request by kraj**
GCC PIE works fine

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
@alistair23 here we go.

**Comment by alistair23** [comment]
Cool, I've tested RV32 and don't see anything strange. I'll build the rest overnight and test tomorrow.

**Comment by alistair23** [comment]
I don't see any breakages on anything else

**Comment by kraj** [comment]
does it boot fine too ?

**Comment by alistair23** [comment]
It does boot, but double checking the log I just noticed that u-boot doesn't detect a network on the HiFive Unleased. I'll see if I can figure out why

**Comment by alistair23** [comment]
Ah, that's a u-boot issue.

All working :)

**Pull request merged**
