### PR TITLE
recipes-kernel: Update to the 5.3 kernel

### PR DESCRIPTION
**Pull request by alistair23**
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

### CODE REVIEW

**Comment by alistair23** [comment]
This is a draft PR with kernel 5.3 support. I'm hoping that patches 11, 12 and 13 will be merged into 5.3 so they can be removed.

**Comment by kraj** [comment]
I can certainly try it out.

**Comment by alistair23** [comment]
It doesn't work with 32-bit, looks like 32-bit is again broken in the latest kernel. I'm bisecting now.

**Comment by alistair23** [comment]
I have updated this PR to fix the RV32 failure and commented on the original patch about the issue.

**Comment by kraj** [comment]
Shall we merge it or wait ?

**Comment by alistair23** [comment]
This should wait until the 5.3 release is out. By then I'm hoping to remove a lot of the extra patches.

**Comment by kraj** [comment]
makes sense thanks

**Comment by alistair23** [comment]
The 5.3 kernel has been released. This is ready to merge

**Pull request merged**
