### PR TITLE
qemuriscv64.conf: Pin to linux-riscv again

### PR DESCRIPTION
**Pull request by kraj**
linux-yocto hangs before it reaches console, until that is
fixed we can not switch

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by alistair23** [comment]
I noticed that the console isn't displayed in Linux-yocto-dev.

I do have some patches to improve the console, I'll look into this as well.

**Comment by alistair23** [comment]
I can't reproduce this. The console isn't printed after earlyboot (sending a patch today) but I don't see any hangs. Can you provide more details?

**Comment by kraj** [comment]
Yeah it doesn’t look like a hang per se but it’s console not coming up and freeze

**Comment by alistair23** [comment]
Ah ok, that's just a defconfig issue. I have sent patches to Bruce

**Comment by kraj** [comment]
Alright let me know when that’s merged in master and we can switch back the kernels after validation

**Comment by alistair23** [comment]
Bruce sent the patches out today. I have a big kernel series I'll push out tonight, we can merge it when Bruce's patch propagates into meta.

**Comment by kraj** [comment]
sounds good. Send me a ping when OE-Core lands it

**Pull request merged**
