### PR TITLE
Freedom U540 / HiFive Unleashed development board support

### PR DESCRIPTION
**Pull request by mirzak**
Rebase of https://github.com/kraj/meta-riscv/pull/3 to new location and updated changes.

Note that I have only build tested the freedom-u540 machine, and verified that I did not break the qemu.

### CODE REVIEW

**Comment by mirzak** [comment]
Ooh, noticed some minors to fix. Will push soon again

**Comment by mirzak** [comment]
Did a new force-push right now, sorry for the last minute inconvenience

**Comment by kraj** [comment]
I merged it please check again and see if I got it all. Thank you

**Comment by mirzak** [comment]
You are fast :).

You got my latest changes so all is good

**Comment by kraj** [comment]
no worries, all good qemu is booting fine, once I have board I will start testing your stuff more

**Pull request merged**
